## Graph States
PROJECT_INITILIZATION = "project_initilization"
REQUIREMENT_COLLECTION = "requirement_collection"
GENERATE_CODE = "generate_code"
FALLBACK_GENERATION = "fallback_generation"
SAVE_CODE = "save_code"
REVISE_CODE = "revise_code"
CODE_VALIDATION = "code_validation"
GENERATE_PLAN = "generate_plan"
DOWNLOAD_ARTIFACTS = "download_artifacts"
ERROR="error"
