## Graph States
PROJECT_INITILIZATION = "project_initilization"
REQUIREMENT_COLLECTION = "requirement_collection"
GENERATE_CODE = "generate_code"
FALLBACK_GENERATION = "fallback_generation"
REVIEW_CODE = "review_code"
CODE_VALIDATION = "code_validation"
SAVE_CODE = "save_code"
DOWNLOAD_ARTIFACTS = "download_artifacts"
ERROR="error"
